export type UserRole =
  | "SUPERADMIN"
  | "ADMIN_EMPRESA"
  | "PREVENCIONISTA"
  | "SUPERVISOR"
  | "TRABAJADOR"
  | "AUDITOR"
  | "LECTURA";

export const PERMISSIONS = {
  canReadEmpresa: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canManageEmpresa: ["ADMIN_EMPRESA"],
  canReadTrabajadores: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canCreateTrabajador: ["ADMIN_EMPRESA", "PREVENCIONISTA"],
  canUpdateTrabajador: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR"],
  canReadDocumentacion: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canManageDocumentacion: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR"],
  canReadCumplimiento: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canManageCumplimiento: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR"],
  canReadCapacitaciones: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canManageCapacitaciones: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR"],
  canReadAlertas: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canReadOrganigrama: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canCreateDocumentacion: ["ADMIN_EMPRESA", "PREVENCIONISTA"],
  canDeactivateTrabajador: ["ADMIN_EMPRESA", "PREVENCIONISTA"],
  canReadPermisos: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR", "AUDITOR", "LECTURA"],
  canManagePermisos: ["ADMIN_EMPRESA", "PREVENCIONISTA", "SUPERVISOR"],
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;