import type { DocumentoEmpresa, UsuarioSesionMock } from "./types";

export const USUARIO_LOGUEADO_MOCK: UsuarioSesionMock = {
  nombre: "Administrador NextPrev",
  email: "admin@dicaprev.cl",
};

const NOW = new Date("2026-05-04T10:30:00").toISOString();

function baseHistorial(
  usuario = USUARIO_LOGUEADO_MOCK.nombre,
  usuarioEmail = USUARIO_LOGUEADO_MOCK.email,
  detalle = "Carga inicial del documento"
) {
  return [
    {
      id: `hist-${Math.random().toString(36).slice(2, 8)}`,
      fecha: NOW,
      usuario,
      usuarioEmail,
      accion: "Documento cargado" as const,
      detalle,
    },
  ];
}

export const DOCUMENTOS_EMPRESA_MOCK: DocumentoEmpresa[] = [
  {
    id: "doc-001",
    nombre: "Reglamento Interno de Orden, Higiene y Seguridad",
    categoria: "sst",
    tipo: "RIOHS",
    estado: "vigente",
    fechaEmision: "2026-01-10",
    fechaVencimiento: null,
    tieneVencimiento: false,
    archivoNombre: "riohs-v1.pdf",
    archivoUrl: "#",
    archivoPeso: 1850000,
    archivoTipo: "application/pdf",
    version: "1.0",
    subidoPor: USUARIO_LOGUEADO_MOCK.nombre,
    subidoPorEmail: USUARIO_LOGUEADO_MOCK.email,
    fechaSubida: "2026-01-12T09:45:00",
    actualizadoPor: USUARIO_LOGUEADO_MOCK.nombre,
    fechaActualizacion: "2026-03-01T11:30:00",
    observaciones: "Documento vigente para control corporativo.",
    historial: baseHistorial(USUARIO_LOGUEADO_MOCK.nombre, USUARIO_LOGUEADO_MOCK.email, "Documento base corporativo cargado"),
  },
  {
    id: "doc-002",
    nombre: "Certificado de afiliación Mutual / Ley 16.744",
    categoria: "mutualidad_ley_16744",
    tipo: "Certificado afiliación",
    estado: "vigente",
    fechaEmision: "2026-01-02",
    fechaVencimiento: "2026-12-31",
    tieneVencimiento: true,
    archivoNombre: "certificado-afiliacion-mutual.pdf",
    archivoUrl: "#",
    archivoPeso: 620000,
    archivoTipo: "application/pdf",
    version: "1.0",
    subidoPor: USUARIO_LOGUEADO_MOCK.nombre,
    subidoPorEmail: USUARIO_LOGUEADO_MOCK.email,
    fechaSubida: "2026-01-03T08:12:00",
    actualizadoPor: USUARIO_LOGUEADO_MOCK.nombre,
    fechaActualizacion: "2026-01-03T08:12:00",
    observaciones: "Afiliación activa al organismo administrador.",
    historial: baseHistorial(USUARIO_LOGUEADO_MOCK.nombre, USUARIO_LOGUEADO_MOCK.email, "Afiliación Ley 16.744 registrada"),
  },
  {
    id: "doc-003",
    nombre: "Certificado F30-1",
    categoria: "laborales_previsionales",
    tipo: "F30-1",
    estado: "por_vencer",
    fechaEmision: "2026-03-01",
    fechaVencimiento: "2026-05-20",
    tieneVencimiento: true,
    archivoNombre: "certificado-f30-1-marzo.pdf",
    archivoUrl: "#",
    archivoPeso: 730000,
    archivoTipo: "application/pdf",
    version: "1.0",
    subidoPor: USUARIO_LOGUEADO_MOCK.nombre,
    subidoPorEmail: USUARIO_LOGUEADO_MOCK.email,
    fechaSubida: "2026-03-05T16:20:00",
    actualizadoPor: USUARIO_LOGUEADO_MOCK.nombre,
    fechaActualizacion: "2026-04-15T10:10:00",
    observaciones: "Revisar renovación antes de vencimiento.",
    historial: baseHistorial(USUARIO_LOGUEADO_MOCK.nombre, USUARIO_LOGUEADO_MOCK.email, "F30-1 cargado para control previsional"),
  },
  {
    id: "doc-004",
    nombre: "Matriz IPER",
    categoria: "sst",
    tipo: "Matriz IPER",
    estado: "pendiente_carga",
    fechaEmision: "2026-05-01",
    fechaVencimiento: null,
    tieneVencimiento: false,
    archivoNombre: null,
    archivoUrl: null,
    archivoPeso: null,
    archivoTipo: null,
    version: "1.0",
    subidoPor: USUARIO_LOGUEADO_MOCK.nombre,
    subidoPorEmail: USUARIO_LOGUEADO_MOCK.email,
    fechaSubida: "2026-05-01T09:00:00",
    actualizadoPor: USUARIO_LOGUEADO_MOCK.nombre,
    fechaActualizacion: "2026-05-01T09:00:00",
    observaciones: "Pendiente de carga del archivo oficial.",
    historial: baseHistorial(USUARIO_LOGUEADO_MOCK.nombre, USUARIO_LOGUEADO_MOCK.email, "Documento creado como pendiente de carga"),
  },
  {
    id: "doc-005",
    nombre: "Plan de emergencia",
    categoria: "sst",
    tipo: "Plan de emergencia",
    estado: "pendiente_carga",
    fechaEmision: "2026-05-01",
    fechaVencimiento: null,
    tieneVencimiento: false,
    archivoNombre: null,
    archivoUrl: null,
    archivoPeso: null,
    archivoTipo: null,
    version: "1.0",
    subidoPor: USUARIO_LOGUEADO_MOCK.nombre,
    subidoPorEmail: USUARIO_LOGUEADO_MOCK.email,
    fechaSubida: "2026-05-01T09:05:00",
    actualizadoPor: USUARIO_LOGUEADO_MOCK.nombre,
    fechaActualizacion: "2026-05-01T09:05:00",
    observaciones: "Pendiente de aprobación final para carga.",
    historial: baseHistorial(USUARIO_LOGUEADO_MOCK.nombre, USUARIO_LOGUEADO_MOCK.email, "Documento creado como pendiente de carga"),
  },
  {
    id: "doc-006",
    nombre: "Constitución Comité Paritario",
    categoria: "sst",
    tipo: "Comité Paritario",
    estado: "no_aplica",
    fechaEmision: "2026-01-01",
    fechaVencimiento: null,
    tieneVencimiento: false,
    archivoNombre: null,
    archivoUrl: null,
    archivoPeso: null,
    archivoTipo: null,
    version: "1.0",
    subidoPor: USUARIO_LOGUEADO_MOCK.nombre,
    subidoPorEmail: USUARIO_LOGUEADO_MOCK.email,
    fechaSubida: "2026-01-01T10:00:00",
    actualizadoPor: USUARIO_LOGUEADO_MOCK.nombre,
    fechaActualizacion: "2026-04-01T10:00:00",
    observaciones: "No aplica por dotación actual de la empresa.",
    historial: baseHistorial(USUARIO_LOGUEADO_MOCK.nombre, USUARIO_LOGUEADO_MOCK.email, "Documento marcado inicialmente como no aplica"),
  },
];
