// =====================================================================
//  Biblioteca Documental — Mock data
//  Documentos reales de la empresa, independientes de acreditaciones.
//  Las acreditaciones los consumen según sus plantillas.
// =====================================================================

import type { DocumentoBase } from "@/app/dicaprev/acreditaciones/types";

const HOY = new Date("2026-04-09");

function offset(dias: number): string {
  const d = new Date(HOY);
  d.setDate(d.getDate() + dias);
  return d.toISOString().slice(0, 10);
}

export const BIBLIOTECA_MOCK: DocumentoBase[] = [
  // ── Documentos de EMPRESA ────────────────────────────────────────

  {
    id: "db-001",
    nombre: "RUT Empresa",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: "2022-01-01",
    estado: "completo",
    archivoUrl: "/mock/rut-empresa.pdf",
    nombreArchivo: "RUT_Empresa.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2022-01-01",
  },
  {
    id: "db-002",
    nombre: "Escritura de Constitución Social",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: "2022-01-01",
    estado: "completo",
    archivoUrl: "/mock/escritura.pdf",
    nombreArchivo: "Escritura_Constitucion.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2022-01-01",
  },
  {
    id: "db-003",
    nombre: "Certificado de Vigencia Empresa",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-30),
    fechaVencimiento: offset(60),
    estado: "completo",
    archivoUrl: "/mock/vigencia-empresa.pdf",
    nombreArchivo: "Certificado_Vigencia.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-30),
  },
  {
    id: "db-004",
    nombre: "Nómina de Trabajadores",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-15),
    estado: "completo",
    archivoUrl: "/mock/nomina.pdf",
    nombreArchivo: "Nomina_Trabajadores.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-15),
  },
  {
    id: "db-005",
    nombre: "Certificado Sin Deuda Tributaria (SII)",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-20),
    fechaVencimiento: offset(40),
    estado: "completo",
    archivoUrl: "/mock/sin-deuda-sii.pdf",
    nombreArchivo: "Sin_Deuda_Tributaria.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-20),
  },
  {
    id: "db-006",
    nombre: "Certificado deuda Tesorería",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-12),
    fechaVencimiento: offset(18),
    estado: "completo",
    archivoUrl: "/mock/tesoreria.pdf",
    nombreArchivo: "Deuda_Tesoreria.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-12),
  },
  {
    id: "db-007",
    nombre: "Mutualidad / Organismo Administrador",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-45),
    fechaVencimiento: offset(-5),
    estado: "vencido",
    archivoUrl: "/mock/mutualidad.pdf",
    nombreArchivo: "Mutualidad.pdf",
    reusableEnAcreditaciones: true,
    observaciones: "Documento vencido — renovar antes de enviar.",
    creadoEl: offset(-45),
  },
  {
    id: "db-008",
    nombre: "Certificado SENCE",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-60),
    fechaVencimiento: offset(90),
    estado: "completo",
    archivoUrl: "/mock/sence.pdf",
    nombreArchivo: "SENCE.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-60),
  },
  {
    id: "db-009",
    nombre: "Certificado de Deuda Previsional (PREVIRED)",
    categoria: "empresa",
    aplicaA: "empresa",
    fechaEmision: offset(-10),
    fechaVencimiento: offset(20),
    estado: "completo",
    archivoUrl: "/mock/previred.pdf",
    nombreArchivo: "Previred_Empresa.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-10),
  },

  // ── Documentos SST ───────────────────────────────────────────────

  {
    id: "db-101",
    nombre: "RIOHS Empresa",
    categoria: "sst",
    aplicaA: "empresa",
    fechaEmision: "2025-07-01",
    fechaVencimiento: "2027-07-01",
    estado: "completo",
    archivoUrl: "/mock/riohs.pdf",
    nombreArchivo: "RIOHS.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2025-07-01",
  },
  {
    id: "db-102",
    nombre: "Certificado Mutual Vigente",
    categoria: "sst",
    aplicaA: "empresa",
    fechaEmision: offset(-5),
    fechaVencimiento: offset(25),
    estado: "completo",
    archivoUrl: "/mock/mutual-vigente.pdf",
    nombreArchivo: "Mutual_Vigente.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-5),
  },
  {
    id: "db-103",
    nombre: "Reglamento interno RIOHS",
    categoria: "sst",
    aplicaA: "empresa",
    fechaEmision: "2025-07-01",
    fechaVencimiento: "2027-07-01",
    estado: "completo",
    archivoUrl: "/mock/reglamento-riohs.pdf",
    nombreArchivo: "Reglamento_RIOHS.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2025-07-01",
  },
  {
    id: "db-104",
    nombre: "Seguro de Accidentes (ACHS/ISL)",
    categoria: "sst",
    aplicaA: "empresa",
    fechaEmision: offset(-20),
    fechaVencimiento: offset(345),
    estado: "completo",
    archivoUrl: "/mock/seguro-achs.pdf",
    nombreArchivo: "Seguro_Accidentes.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-20),
  },

  // ── Documentos por TRABAJADOR ────────────────────────────────────
  // Trabajador w-001: Carlos Pérez Mora

  {
    id: "db-201",
    nombre: "Cédula de Identidad (vigente)",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-001",
    titularNombre: "Carlos Pérez Mora",
    fechaEmision: "2022-03-15",
    fechaVencimiento: "2030-03-15",
    estado: "completo",
    archivoUrl: "/mock/ci-w001.pdf",
    nombreArchivo: "CI_Carlos_Perez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2022-03-15",
  },
  {
    id: "db-202",
    nombre: "Contrato de Trabajo",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-001",
    titularNombre: "Carlos Pérez Mora",
    fechaEmision: "2024-01-01",
    estado: "completo",
    archivoUrl: "/mock/contrato-w001.pdf",
    nombreArchivo: "Contrato_Carlos_Perez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2024-01-01",
  },
  {
    id: "db-203",
    nombre: "Certificado AFP",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-001",
    titularNombre: "Carlos Pérez Mora",
    fechaEmision: offset(-8),
    fechaVencimiento: offset(22),
    estado: "completo",
    archivoUrl: "/mock/afp-w001.pdf",
    nombreArchivo: "AFP_Carlos_Perez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-8),
  },
  {
    id: "db-204",
    nombre: "Certificado ISAPRE/FONASA",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-001",
    titularNombre: "Carlos Pérez Mora",
    fechaEmision: offset(-8),
    fechaVencimiento: offset(22),
    estado: "completo",
    archivoUrl: "/mock/isapre-w001.pdf",
    nombreArchivo: "Salud_Carlos_Perez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-8),
  },
  {
    id: "db-205",
    nombre: "ODI Firmada",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-001",
    titularNombre: "Carlos Pérez Mora",
    fechaEmision: "2024-01-05",
    estado: "completo",
    archivoUrl: "/mock/odi-w001.pdf",
    nombreArchivo: "ODI_Carlos_Perez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2024-01-05",
  },

  // Trabajador w-002: Ana Ruiz González

  {
    id: "db-211",
    nombre: "Cédula de Identidad (vigente)",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-002",
    titularNombre: "Ana Ruiz González",
    fechaEmision: "2023-06-01",
    fechaVencimiento: "2031-06-01",
    estado: "completo",
    archivoUrl: "/mock/ci-w002.pdf",
    nombreArchivo: "CI_Ana_Ruiz.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2023-06-01",
  },
  {
    id: "db-212",
    nombre: "Contrato de Trabajo",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-002",
    titularNombre: "Ana Ruiz González",
    fechaEmision: "2024-03-01",
    estado: "completo",
    archivoUrl: "/mock/contrato-w002.pdf",
    nombreArchivo: "Contrato_Ana_Ruiz.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2024-03-01",
  },
  {
    id: "db-213",
    nombre: "Certificado AFP",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-002",
    titularNombre: "Ana Ruiz González",
    fechaEmision: offset(-10),
    fechaVencimiento: offset(-2),
    estado: "vencido",
    archivoUrl: "/mock/afp-w002.pdf",
    nombreArchivo: "AFP_Ana_Ruiz.pdf",
    reusableEnAcreditaciones: true,
    observaciones: "Venció hace 2 días — renovar urgente.",
    creadoEl: offset(-10),
  },

  // Trabajador w-003: Pedro Contreras (sin algunos docs — faltantes)

  {
    id: "db-221",
    nombre: "Cédula de Identidad (vigente)",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-003",
    titularNombre: "Pedro Contreras López",
    fechaEmision: "2021-09-10",
    fechaVencimiento: "2029-09-10",
    estado: "completo",
    archivoUrl: "/mock/ci-w003.pdf",
    nombreArchivo: "CI_Pedro_Contreras.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2021-09-10",
  },

  // Trabajador w-004: Juan López Soto

  {
    id: "db-231",
    nombre: "Cédula de Identidad (vigente)",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-004",
    titularNombre: "Juan López Soto",
    fechaEmision: "2022-11-20",
    fechaVencimiento: "2030-11-20",
    estado: "completo",
    archivoUrl: "/mock/ci-w004.pdf",
    nombreArchivo: "CI_Juan_Lopez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2022-11-20",
  },
  {
    id: "db-232",
    nombre: "Licencia Eléctrica SEC",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-004",
    titularNombre: "Juan López Soto",
    fechaEmision: offset(-90),
    fechaVencimiento: offset(275),
    estado: "completo",
    archivoUrl: "/mock/sec-w004.pdf",
    nombreArchivo: "Licencia_SEC_Juan_Lopez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-90),
  },
  {
    id: "db-233",
    nombre: "Licencia eléctrica (SEC)",
    categoria: "trabajador",
    aplicaA: "trabajador",
    titularId: "w-004",
    titularNombre: "Juan López Soto",
    fechaEmision: offset(-90),
    fechaVencimiento: offset(275),
    estado: "completo",
    archivoUrl: "/mock/sec-w004.pdf",
    nombreArchivo: "Licencia_SEC_Juan_Lopez.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: offset(-90),
  },

  // ── Documentos VEHÍCULOS ─────────────────────────────────────────
  // Vehículo v-001: Toyota Hilux BPZK-12

  {
    id: "db-301",
    nombre: "Permiso de Circulación",
    categoria: "vehiculo",
    aplicaA: "vehiculo",
    titularId: "v-001",
    titularNombre: "Toyota Hilux (BPZK-12)",
    fechaEmision: "2026-03-01",
    fechaVencimiento: "2027-03-01",
    estado: "completo",
    archivoUrl: "/mock/permiso-v001.pdf",
    nombreArchivo: "Permiso_Circulacion_BPZK12.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2026-03-01",
  },
  {
    id: "db-302",
    nombre: "SOAP Vigente",
    categoria: "vehiculo",
    aplicaA: "vehiculo",
    titularId: "v-001",
    titularNombre: "Toyota Hilux (BPZK-12)",
    fechaEmision: "2026-03-01",
    fechaVencimiento: "2027-03-01",
    estado: "completo",
    archivoUrl: "/mock/soap-v001.pdf",
    nombreArchivo: "SOAP_BPZK12.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2026-03-01",
  },
  {
    id: "db-303",
    nombre: "Revisión Técnica y Gases",
    categoria: "vehiculo",
    aplicaA: "vehiculo",
    titularId: "v-001",
    titularNombre: "Toyota Hilux (BPZK-12)",
    fechaEmision: "2025-11-15",
    fechaVencimiento: offset(-8),
    estado: "vencido",
    archivoUrl: "/mock/revision-v001.pdf",
    nombreArchivo: "Revision_Tecnica_BPZK12.pdf",
    reusableEnAcreditaciones: true,
    observaciones: "Revisión técnica vencida — tramitar antes de acreditar.",
    creadoEl: "2025-11-15",
  },

  // Vehículo v-002: Ford Ranger RTHJ-45

  {
    id: "db-311",
    nombre: "Permiso de Circulación",
    categoria: "vehiculo",
    aplicaA: "vehiculo",
    titularId: "v-002",
    titularNombre: "Ford Ranger (RTHJ-45)",
    fechaEmision: "2026-03-01",
    fechaVencimiento: "2027-03-01",
    estado: "completo",
    archivoUrl: "/mock/permiso-v002.pdf",
    nombreArchivo: "Permiso_Circulacion_RTHJ45.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2026-03-01",
  },
  {
    id: "db-312",
    nombre: "SOAP Vigente",
    categoria: "vehiculo",
    aplicaA: "vehiculo",
    titularId: "v-002",
    titularNombre: "Ford Ranger (RTHJ-45)",
    fechaEmision: "2026-03-01",
    fechaVencimiento: "2027-03-01",
    estado: "completo",
    archivoUrl: "/mock/soap-v002.pdf",
    nombreArchivo: "SOAP_RTHJ45.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2026-03-01",
  },
  {
    id: "db-313",
    nombre: "Revisión Técnica y Gases",
    categoria: "vehiculo",
    aplicaA: "vehiculo",
    titularId: "v-002",
    titularNombre: "Ford Ranger (RTHJ-45)",
    fechaEmision: "2026-01-10",
    fechaVencimiento: offset(180),
    estado: "completo",
    archivoUrl: "/mock/revision-v002.pdf",
    nombreArchivo: "Revision_Tecnica_RTHJ45.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2026-01-10",
  },

  // ── Documentos ANEXOS ────────────────────────────────────────────

  {
    id: "db-401",
    nombre: "Protocolo COVID-19 Empresa",
    categoria: "anexo",
    aplicaA: "empresa",
    fechaEmision: "2023-01-01",
    estado: "completo",
    archivoUrl: "/mock/protocolo-covid.pdf",
    nombreArchivo: "Protocolo_COVID.pdf",
    reusableEnAcreditaciones: true,
    creadoEl: "2023-01-01",
  },
];
