export {
  getVehiculos,
  getVehiculoById,
  getVehiculoDocumentos,
  getDocumentosVehiculo,
  getVehiculoMantenciones,
  getVehiculoDetalle,
  getTiposDocumentoVehiculo,
  getCentrosList,
  getResponsablesVehiculoList,
  crearVehiculo,
  actualizarVehiculo,
  eliminarVehiculo,
  upsertVehiculoDocumento,
  crearOActualizarDocumentoVehiculo,
  cambiarEstadoDocumentoVehiculo,
  eliminarDocumentoVehiculo,
  evaluarDocumentosVehiculo,
  crearMantencionVehiculo,
} from "@/app/dicaprev/empresa/vehiculos/actions";

export type {
  VehiculoDTO,
  VehiculoDocumentoDTO,
  EstadoDocumentoVehiculo,
  VehiculoMantencionDTO,
  VehiculoInput,
  DocumentoVehiculoInput,
  MantencionVehiculoInput,
  CentroItem,
  ResponsableVehiculoItem,
  MantencionEstado,
} from "@/app/dicaprev/empresa/vehiculos/actions";
